"""Route-contract snapshot test (M0 safety net for Media Routes Split).

Captures a normalized contract per `(method, path)`:
  - HTTP method (uppercase)
  - URL path template (FastAPI/OpenAPI form, e.g. `/api/books/{book_id}`)
  - ``requires_auth`` (bool — derived from operation.security presence)
  - ``has_request_body`` (bool)
  - ``responses`` (sorted list of HTTP status codes declared by the route)

Volatile fields (descriptions, summaries, schema $ref payloads, operationId,
tags) are intentionally excluded so the snapshot remains stable across the
refactor. The goal is to detect *contract drift* — a route disappearing,
its method changing, becoming public when it was protected, or losing its
``200`` response — not to lock down documentation copy.

Stability guarantees:
* Output deterministically ordered by ``(path, method)``.
* Pure stdlib (json, pathlib) — no new dependency.
* Bootstrap-friendly: when `UPDATE_ROUTE_SNAPSHOT=1`, the snapshot file is
  regenerated; otherwise the test asserts equality and surfaces a unified
  diff hint.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from server import app


SNAPSHOT_PATH = Path(__file__).parent / "snapshots" / "route_contracts.json"

# Internal paths we don't want to track (auto-generated by FastAPI/Starlette).
_IGNORED_PATHS = {"/openapi.json", "/docs", "/redoc", "/docs/oauth2-redirect"}


def _build_contract_map() -> dict:
    """Reduce the OpenAPI schema to a stable per-route contract."""
    schema = app.openapi()
    paths = schema.get("paths", {})

    contracts: dict[str, dict] = {}
    for path, methods in paths.items():
        if path in _IGNORED_PATHS:
            continue
        for method, op in methods.items():
            if method.lower() not in {
                "get", "post", "put", "delete", "patch", "head", "options",
            }:
                continue
            method_u = method.upper()
            key = f"{method_u} {path}"
            contracts[key] = {
                "method": method_u,
                "path": path,
                "requires_auth": bool(op.get("security")),
                "has_request_body": "requestBody" in op,
                "responses": sorted((op.get("responses") or {}).keys()),
            }

    # Stable ordering: sort by key.
    return {k: contracts[k] for k in sorted(contracts.keys())}


def _serialize(contract_map: dict) -> str:
    return json.dumps(contract_map, indent=2, sort_keys=True) + "\n"


def test_route_contract_snapshot_matches():
    """The current route contract MUST match the committed snapshot.

    Run with ``UPDATE_ROUTE_SNAPSHOT=1`` to refresh the snapshot after an
    intentional contract change.
    """
    current = _build_contract_map()
    current_serialized = _serialize(current)

    if os.environ.get("UPDATE_ROUTE_SNAPSHOT") == "1":
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(current_serialized)
        return

    assert SNAPSHOT_PATH.exists(), (
        f"Snapshot missing at {SNAPSHOT_PATH}. "
        "Bootstrap once with `UPDATE_ROUTE_SNAPSHOT=1 pytest tests/test_route_contract.py`."
    )

    expected_serialized = SNAPSHOT_PATH.read_text()
    if current_serialized != expected_serialized:
        # Find specific drift to make the diff actionable.
        expected = json.loads(expected_serialized)
        added = sorted(set(current) - set(expected))
        removed = sorted(set(expected) - set(current))
        changed = sorted(
            k for k in set(current) & set(expected) if current[k] != expected[k]
        )

        msg_lines = ["Route contract drift detected vs committed snapshot."]
        if removed:
            msg_lines.append(f"  REMOVED routes ({len(removed)}): {removed[:10]}")
        if added:
            msg_lines.append(f"  ADDED routes ({len(added)}): {added[:10]}")
        if changed:
            sample = []
            for k in changed[:5]:
                sample.append(f"    {k}: expected={expected[k]} current={current[k]}")
            msg_lines.append(f"  CHANGED routes ({len(changed)}):")
            msg_lines.extend(sample)
        msg_lines.append(
            "If the change is intentional, refresh the snapshot with "
            "`UPDATE_ROUTE_SNAPSHOT=1 pytest tests/test_route_contract.py`."
        )
        raise AssertionError("\n".join(msg_lines))


def test_route_contract_snapshot_contains_media_endpoints():
    """Sanity guard: the 12 anchor media routes targeted by M1 MUST exist.

    This is a belt-and-suspenders check on top of the snapshot equality
    above: if the snapshot is regenerated mid-refactor, the anchor list
    here still requires every M1 endpoint to be present (under whatever
    router it lives in).
    """
    current = _build_contract_map()
    anchors = [
        # Themes media
        "GET /api/themes/{theme_id}/background-image",
        "POST /api/admin/themes/{theme_id}/upload-background",
        # Illustrations media
        "GET /api/search/illustrations",
        "POST /api/illustrations/{illustration_id}/download",
        "GET /api/illustrations/{illustration_id}/download-status",
        "GET /api/illustrations/{illustration_id}/image",
        "GET /api/illustrations/{illustration_id}/image-status",
        "POST /api/admin/illustrations/{illustration_id}/attach-pdf",
        "POST /api/admin/illustrations/{illustration_id}/attach-image",
        "POST /api/admin/generate-illustration",
        "PUT /api/admin/illustrations/{illustration_id}/theme",
        # Bundles media
        "GET /api/bundles/{bundle_id}/background-image",
        "GET /api/bundles/{bundle_id}/download",
        "GET /api/bundles/{bundle_id}/download-pdf",
        "POST /api/admin/bundles/{bundle_id}/upload-background",
        "POST /api/admin/bundles/{bundle_id}/upload-pdf",
    ]
    missing = [a for a in anchors if a not in current]
    assert not missing, (
        f"Anchor media routes missing from the live app: {missing}"
    )
